name: Build for Windows 64-bit

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    
    - name: setup-go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13'
      
    - name: setup-env
      run: |
        echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
        echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash
      
    - uses: actions/checkout@master
      name: checkout
        
    - name: setup-bin-folder
      run: mkdir bin
      
    - name: setup-deps
      run: |
        go get github.com/kardianos/service
        go get github.com/mitchellh/go-ps
      
    - name: build-for-windows
      run: |
        go build
        dir ohsw.exe
      env:
        GOOS: windows
        GOARCH: amd64
        
    - name: copy-to-bin-folder
      run: copy ohsw.exe bin
      
    - uses: actions/upload-artifact@master
      with:
         name: ohsw
         path: bin
      name: upload-artefact
      
    - name: zip-it
      run: Compress-Archive -Path bin -DestinationPath ohsw.zip

    - name: upload-release-asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ohsw.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
