name: Build for Windows 64-bit

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      name: checkout
      
    - name: setup-go
      uses: actions/setup-go@v1
      with:
        go-version: '^1.13'
        
    - run: mkdir bin
      name setup-bin-folder
      
    - run: go build -o ./bin/ohsw.exe ohsw.go
      name: build-for-windows
      env:
        GOOS: windows
        GOARCH: amd64
      
    - uses: actions/upload-artifact@master
      with:
         name: ohsw
         path: bin
      name: upload-artefact
