name: Build for Windows 64-bit

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: setup-go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13'
      
    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
        echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash
      
    - uses: actions/checkout@master
      name: checkout
        
    - name: setup-bin-folder
      run: mkdir bin
      
    - name: setup-deps
      run: |
        echo $(go env GOPATH)
        echo $(go env GOROOT)
        go get -v -u ./...
      
    - name: build-for-windows
      run: go build
      env:
        GOOS: windows
        GOARCH: amd64
      
    #- uses: actions/upload-artifact@master
    #  with:
    #     name: ohsw
    #     path: bin
    #  name: upload-artefact
