name: Build for Windows 64-bit

on:
  push:
    branches: [master]

jobs:

jobs:
  check:
    runs-on: ubuntu-latest
    
    outputs:
      status: ${{ steps.check.outputs.status }}
      upload_url: ${{ steps.create.outputs.upload_url }}
        
    - name: create-release
      id: create
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-${{ steps.check.outputs.version }}
        release_name: Nightly build from ${{ steps.check.outputs.version }}
        prerelease: true
        commitish: ${{ env.GITHUB_SHA }}

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      name: checkout
    
    - name: setup-go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13'
      
    - name: setup-env
      run: |
        echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
        echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash
      
    - name: setup-bin-folder
      run: mkdir bin
      
    - name: setup-deps
      run: |
        go get github.com/kardianos/service
        go get github.com/mitchellh/go-ps
      
    - name: build-for-windows
      run: |
        go build
        dir ohsw.exe
      env:
        GOOS: windows
        GOARCH: amd64
        
    - name: copy-to-bin-folder
      run: copy ohsw.exe bin
      
    - name: Upload Windows Build
      id: upload-win
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.check.outputs.upload_url }}
        asset_path: bin/ohsw.exe
        asset_name: ohsw.exe
        asset_content_type: application/octet-stream
