name: Build for Windows 64-bit

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      name: checkout
      
    - name: setup-go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13'
        
    - name: setup-bin-folder
      run: mkdir bin
      
    - name: build-for-windows
      run: go build
      env:
        GOOS: windows
        GOARCH: amd64
      
    #- uses: actions/upload-artifact@master
    #  with:
    #     name: ohsw
    #     path: bin
    #  name: upload-artefact
